# Generated by Django 3.1.5 on 2021-12-16 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211118_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 5, 36, 52, 951291, tzinfo=utc)),
        ),
    ]
